
spring:
  docker:
    compose:
      enabled: true
      file: selenium-standalone-firefox.yml

web-driver:
  browser: FIREFOX
  remote:
    enabled: true
    address: http://localhost:4444/wd/hub
    tracing-enabled: true